project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  title: "Yangqi's website"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/bio-info-guy
      - icon: twitter
        href: https://x.com/yqsu_bioinfo
      - icon: linkedin
        href: https://www.linkedin.com/in/yangqi-su-a70745162/
format:
  html:
    theme: cosmo
    css: styles.css



